version: "3.3"
services:
    api:
        build: ./api
        container_name: api
        command: gunicorn -b 0.0.0.0:8000 rateyard_api:create_app() --access-logfile /var/log/gunicorn.log
        ports: 
            - 8000:8000
        external_links: 
            - db:docker-postgresql
    front:
        build: ./front
        container_name: front
        command: gunicorn -b 0.0.0.0:80 frontik:create_app() --access-logfile /var/log/gunicorn.log
        ports: 
            - 80:80
        external_links: 
            - api:docker-api
    db:
        image: postgres
        container_name: db
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: rateyard
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./db/data:/var/lib/postgresql/data
        ports:
            - 5432:5432
