version: "3.3"
services:
    api:
        build: ./api
        command: gunicorn -b 0.0.0.0:8000 rateyard_api:create_app()
        ports: 
            - 8000:8000
        external_links: 
            - db:docker-postgresql
        depends_on:
            - db
    front:
        build: ./front
        command: gunicorn -b 0.0.0.0:80 frontik:create_app()
        ports: 
            - 80:80
        external_links: 
            - api:docker-api
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: rateyard
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432
