version: "3.3"
services:
    api:
        restart: always
        build: ./api
        command: gunicorn -b 0.0.0.0:8000 wsgi:create_app()
        external_links: 
            - db:docker-postgresql
        depends_on:
            - db
    front:
        restart: always
        build: ./front
        command: bash -c "service nginx start && /usr/sbin/php-fpm7.4 --nodaemonize --fpm-config /etc/php/7.4/fpm/php-fpm.conf"
        depends_on:
            - api
        external_links:
            - api:docker-api
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_DB: rateyard
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    webserver:
        build: webserver
        restart: unless-stopped
        ports:
            - 80:80
        external_links:
            - api:docker-api
            - front:docker-front
